# TP1 Apprentissage Automatique 
## Mathilde MOTTAY

### Pour commencer

In [1]:
from sklearn import datasets 
iris = datasets.load_iris()
print (iris.data)
print (iris.target)

ModuleNotFoundError: No module named 'sklearn'

### 1) Division de l'échantillon d'apprentissage 

Etant donné que les données sont triées par classe, il faut d'abord les mélanger.

In [110]:
import numpy as np
import scipy.stats

Ciris = np.c_[iris.data.reshape(len(iris.data), -1), iris.target.reshape(len(iris.target), -1)]
np.random.seed(987654321)
np.random.shuffle(Ciris)
shuffledIrisData = Ciris[ :, :iris.data.size//len(iris.data)].reshape(iris.data.shape)
shuffledIrisTarget = Ciris[ :, iris.data.size//len(iris.data) :].reshape(iris.target.shape)
print (shuffledIrisData)

[[4.8 3.4 1.6 0.2]
 [5.5 2.5 4.  1.3]
 [6.3 3.3 4.7 1.6]
 [6.1 2.8 4.7 1.2]
 [5.1 3.8 1.6 0.2]
 [6.6 3.  4.4 1.4]
 [5.8 2.6 4.  1.2]
 [6.6 2.9 4.6 1.3]
 [5.1 2.5 3.  1.1]
 [5.2 3.5 1.5 0.2]
 [7.2 3.2 6.  1.8]
 [7.2 3.  5.8 1.6]
 [5.1 3.3 1.7 0.5]
 [7.2 3.6 6.1 2.5]
 [6.4 2.8 5.6 2.2]
 [5.6 2.9 3.6 1.3]
 [6.2 3.4 5.4 2.3]
 [5.1 3.5 1.4 0.2]
 [4.8 3.1 1.6 0.2]
 [6.7 3.  5.2 2.3]
 [4.6 3.2 1.4 0.2]
 [4.6 3.4 1.4 0.3]
 [6.1 2.8 4.  1.3]
 [5.7 2.8 4.5 1.3]
 [5.9 3.  4.2 1.5]
 [4.8 3.  1.4 0.1]
 [4.5 2.3 1.3 0.3]
 [5.5 2.6 4.4 1.2]
 [5.7 2.5 5.  2. ]
 [6.4 3.1 5.5 1.8]
 [6.3 2.9 5.6 1.8]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.3 3.7 1.5 0.2]
 [5.2 2.7 3.9 1.4]
 [5.1 3.5 1.4 0.3]
 [7.7 2.8 6.7 2. ]
 [6.3 2.5 4.9 1.5]
 [6.7 3.1 4.4 1.4]
 [6.  3.4 4.5 1.6]
 [5.7 3.8 1.7 0.3]
 [6.9 3.1 5.4 2.1]
 [6.5 3.  5.8 2.2]
 [5.  3.4 1.6 0.4]
 [4.8 3.4 1.9 0.2]
 [6.1 2.9 4.7 1.4]
 [4.9 3.6 1.4 0.1]
 [4.9 2.4 3.3 1. ]
 [4.8 3.  1.4 0.3]
 [6.1 3.  4.6 1.4]
 [6.7 3.3 5.7 2.5]
 [6.5 3.  5.5 1.8]
 [5.5 2.4 3.

### 2) Phase d'apprentissage

##### Utilisation des données d'apprentissage (100 premiers exemples) et leur classe afin de déterminer les paramètres de notre classifieur Bayésien

Estimation des probabilités à priori : 

In [118]:
data = shuffledIrisData[:100]
target = shuffledIrisTarget[:100]

# Compteur 
cptSetosa = 0
cptVersicolor = 0
cptVirginica = 0

for f in target: 
    if f == 0:
        cptSetosa += 1
    elif f == 1:
        cptVersicolor += 1
    else :
        cptVirginica += 1

print ("Compteur Setosa = ", cptSetosa)
print ("Compteur Versicolor = ", cptVersicolor)
print ("Compteur Virginica = ", cptVirginica)

# Calcul probabilité à priori 
total = cptSetosa + cptVersicolor + cptVirginica 
pSetosa = cptSetosa/total
pVersicolor = cptVersicolor/total
pVirginica = cptVirginica/total
print ("\nProbabilité à priori Setosa = ", pSetosa)
print ("Probabilité à priori Versicolor = ", pVersicolor)
print ("Probabilité à priori Virginica = ", pVirginica)

Compteur Setosa =  32
Compteur Versicolor =  37
Compteur Virginica =  31

Probabilité à priori Setosa =  0.32
Probabilité à priori Versicolor =  0.37
Probabilité à priori Virginica =  0.31


Estimation des vraisemblances :

In [105]:
# On récupère pour les sépales leur longueur et largeur 
setosaSepal = [] # 0 pour length et 1 pour width 
versicolorSepal = []
virginicaSepal = []

for i in range(100): 
    length = data[i][0]
    width = data[i][1]
    
    if target[i] == 0: 
        setosaSepal.append([length, width])
    elif target[i] == 1:
        versicolorSepal.append([length, width])
    else: 
        virginicaSepal.append([length, width])
        
# print ("\nSetosa : ", setosaSepal)
# print ("\nVersicolor : ", versicolorSepal)
# print ("\nVirginica : ", virginicaSepal)

# Moyenne des longueurs et largeurs des sépales 
moySetosa = np.mean(setosaSepal,0)
moyVersicolor = np.mean(versicolorSepal,0)
moyVirginica = np.mean(virginicaSepal,0)
print ("\nMoyenne Setosa [length, width] : " , moySetosa)
print ("Moyenne Versicolor [length, width] : " , moyVersicolor)
print ("Moyenne Virginica [length, width] : " , moyVirginica)

# Variance des longueurs et largeurs des sépales 
print ("\nVariance Setosa [length, width] : ", np.var(setosaSepal,0, ddof = 1)) # ddof = 1 pour diviser par N-1
print ("Variance Versicolor [length, width] : ", np.var(versicolorSepal,0, ddof = 1))
print ("Variance Virginica [length, width] : ", np.var(virginicaSepal,0, ddof = 1))

# Covariance des longueurs et largeurs des sépales (
# Pas utile car on est dans le modèle bayésien naïf donc la variance et la moyenne suffisent)
# Remarque : On retrouve les variances dans la diagonale. 
print ("\nCovariance Setosa")
print(np.cov(np.transpose(setosaSepal)[0], np.transpose(setosaSepal)[1]))
print ("\nCovariance Versicolor")
print(np.cov(np.transpose(versicolorSepal)[0], np.transpose(versicolorSepal)[1]))
print ("\nCovariance Virginica")
print(np.cov(np.transpose(virginicaSepal)[0], np.transpose(virginicaSepal)[1]))

stdSetosa = np.std(setosaSepal,0, ddof = 1)
stdVersicolor = np.std(versicolorSepal,0, ddof = 1)
stdVirginica = np.std(virginicaSepal,0, ddof = 1)
# Ecart-type 
print ("\nEcart-type Setosa : ", stdSetosa)
print ("Ecart-type Versicolor : ", stdVersicolor)
print ("Ecart-type Virginica : ", stdVirginica)


Moyenne Setosa [length, width] :  [4.971875 3.40625 ]
Moyenne Versicolor [length, width] :  [5.82972973 2.75405405]
Moyenne Virginica [length, width] :  [6.54516129 3.01612903]

Variance Setosa [length, width] :  [0.10595766 0.12189516]
Variance Versicolor [length, width] :  [0.24436937 0.10144144]
Variance Virginica [length, width] :  [0.28589247 0.09073118]

Covariance Setosa
[[0.10595766 0.07824597]
 [0.07824597 0.12189516]]

Covariance Versicolor
[[0.24436937 0.09529279]
 [0.09529279 0.10144144]]

Covariance Virginica
[[0.28589247 0.08824731]
 [0.08824731 0.09073118]]

Ecart-type Setosa :  [0.32551138 0.34913488]
Ecart-type Versicolor :  [0.4943373  0.31849873]
Ecart-type Virginica :  [0.53468914 0.30121617]


In [125]:
l = 4.8
w = 3.0

print ("J'ai un iris avec les données suivantes : l = ", l, " et w = ", w)
# SETOSA 
pSetosaLength = scipy.stats.norm.pdf(l,moySetosa[0],stdSetosa[0])
pSetosaWidth = scipy.stats.norm.pdf(w,moySetosa[1],stdSetosa[1])
probaSetosa = pSetosaLength * pSetosaWidth * pSetosa 
print ("Proba que l'iris soit un Setosa = ", probaSetosa)

# VERSICOLOR
pVersicolorLength = scipy.stats.norm.pdf(l,moyVersicolor[0],stdVersicolor[0])
pVersicolorWidth = scipy.stats.norm.pdf(w,moyVersicolor[1],stdVersicolor[1])
probaVersicolor = pVersicolorLength * pVersicolorWidth * pVersicolor 
print ("Proba que l'iris soit un Versicolor = ", probaVersicolor)


# VIRGINICA
pVirginicaLength = scipy.stats.norm.pdf(l,moyVirginica[0],stdVirginica[0])
pVirginicaWidth = scipy.stats.norm.pdf(w,moyVirginica[1],stdVirginica[1])
probaVirginica = pVirginicaLength * pVirginicaWidth * pVirginica 
print ("Proba que l'iris soit un Virginica = ", probaVirginica)


J'ai un iris avec les données suivantes : l =  4.8  et w =  3.0
Proba que l'iris soit un Setosa =  0.19809115506036956
Proba que l'iris soit un Versicolor =  0.03170898726536254
Proba que l'iris soit un Virginica =  0.0014870606711950907


### 3) Phase de développement

### 4) Phase d'évaluation